# Generated by Django 4.2.5 on 2023-09-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel',
            new_name='Category',
        ),
    ]
