# Generated by Django 4.2.5 on 2023-09-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0002_rename_carousel_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Carousel',
        ),
    ]
