# Generated by Django 4.2.5 on 2023-09-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0008_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mystoreapp.subcategory'),
            preserve_default=False,
        ),
    ]
