# Generated by Django 4.2.5 on 2023-09-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0012_remove_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mystoreapp.series'),
        ),
    ]
