# Generated by Django 4.2.5 on 2023-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0014_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='mystoreapp.product')),
            ],
        ),
    ]
