# Generated by Django 4.2.5 on 2024-01-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0027_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
    ]
