# Generated by Django 4.2.5 on 2024-01-24 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystoreapp', '0029_billingdetails_remove_cart_products_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(blank=True, default={'objects': []}, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Dispatch'), (3, 'On the way'), (4, 'Delivered'), (5, 'Cancel'), (6, 'Return')], default=1)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment_suite_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('town_city', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
    ]
