# Generated by Django 4.2.5 on 2024-02-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0032_remove_deliveryagent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
