# Generated by Django 5.0.1 on 2024-02-12 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystoreapp', '0034_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='deliveryagent',
            name='place',
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=15),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='email',
            field=models.EmailField(default='manjarijayan2024@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='license_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagent',
            name='vechicle_type',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
